### ISSUE TITLE
Foreman support

### ISSUE THREAD

**Issue by ARNHOE** [sensson/sensson-directadmin#1]
Currently, I cannot set any config values in Foreman. There is no directadmin::config

Is this supported or am I doing something wrong?

**Comment by sensson** [comment]
The module itself is not written with Foreman in mind. It does support Hiera and as such Foreman could work with similar hashes as well, but the easiest solution would be to write your own profiles module with your own class, e.g. `profiles::directadmin::config`, that simply runs `directadmin::config::set` a few times. If you set up parameters for that class you can import them into Foreman as Smart Variables and you're pretty much done. The same goes for `directadmin::custombuild::set` by the way. If you want to manage admin and reseller users from Foreman you could use `create_resources` instead with a similar structure, but instead of using fixed variables a hash would probably be easier.

So even though the module has no support for Foreman, it is possible to use it.
